export const actionTypes = {
    FETCH_CHARACTERS: 'FETCH_CHARACTERS',
    FETCH_CHARACTER: 'FETCH_CHARACTER',
    FETCH_ONE_CHARACTER: 'FETCH_ONE_CHARACTER',
    LOCAL_STORAGE_CHARACTER: 'LOCAL_STORAGE_CHARACTER',
    LOCAL_STORAGE_DELETE: 'LOCAL_STORAGE_DELETE'
}